version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'race-api'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'

  devapp:
    restart: unless-stopped
    depends_on:
      - mysql
    image: ambientum/php:7.3-nginx
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED}
    links:
      - mysql
    volumes:
      - './:/var/www/app'
      - '${HOME}/.composer/:/home/ambientum/.composer/'
    ports:
      - '8081:8080'
volumes:
  db_data: {}