version: '3'

services:
  postgres:
    image: postgres:10.5
    restart: always
    volumes:
      - './storage/app/postgres/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=race-api
      - POSTGRES_USER=race-api
      - POSTGRES_PASSWORD=race-api
    ports:
      - '5432:5432'

  devapp:
    restart: unless-stopped
    depends_on:
      - postgres
    image: ambientum/php:7.3-nginx
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED}
    links:
      - postgres
    volumes:
      - './:/var/www/app'
      - '${HOME}/.composer/:/home/ambientum/.composer/'
    ports:
      - '8081:8080'
volumes:
  db_data: {}